fullnameOverride: demo-web

replicaCount: 1

profile: default

namespace: default

image:
  repository: devosquickstarter/eks-demo-web
  tag: latest
  pullPolicy: Always

dockerRegistrySecret: regcred

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: $SERVICE_ACCOUNT
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  labels: {}

autoscaling:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80

resources:
  requests:
    cpu: 800m
    memory: 1024Mi
  limits:
    cpu: 850m
    memory: 1100Mi

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 3

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
pinpoint:
  enabled: false
  collectorIp: pinpoint-collector.monitor.svc.cluster.local

configmap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

wasFullName: demo-was
wasServicePort: 8080
